### ISSUE TITLE
Crash due to missing location in call to date

### ISSUE THREAD

**Issue by ADRFranklin** [davidnewhall/unpackerr#142]
So I've been having this problem for a few months at this point. Hopefully it can be fixed, as this is quite annoying to see it always down. 

```
2021/07/29 18:02:28 Extraction Started: Feels.Like.Ishq.S01E06.1080p.WEB.H264-FORSEE-uk01, items in queue: 9

panic: time: missing Location in call to Date


goroutine 18 [running]:

time.Date(0x7e5, 0x7, 0x17, 0x7, 0x1c, 0x36, 0x0, 0x0, 0x8cbce0, 0xc000613601, ...)

	/usr/local/go/src/time/time.go:1344 +0x5f1

github.com/nwaples/rardecode.parseDosTime(0x52f73b9b, 0xc00016a000, 0x0, 0xc00026af60)

	/go/pkg/mod/github.com/nwaples/rardecode@v1.1.0/archive15.go:132 +0x9b

github.com/nwaples/rardecode.(*archive15).parseFileHeader(0xc0000901a0, 0xc0005a17d0, 0xc00026afc0, 0x97af60, 0xc00026afc0)

	/go/pkg/mod/github.com/nwaples/rardecode@v1.1.0/archive15.go:278 +0x2a7

github.com/nwaples/rardecode.(*archive15).next(0xc0000901a0, 0x40e078, 0xc000048c00, 0x0)

	/go/pkg/mod/github.com/nwaples/rardecode@v1.1.0/archive15.go:430 +0x345

github.com/nwaples/rardecode.(*volume).next(0xc00047a150, 0x0, 0x0, 0x0)

	/go/pkg/mod/github.com/nwaples/rardecode@v1.1.0/archive.go:232 +0x5b

github.com/nwaples/rardecode.(*packedFileReader).next(0xc000272418, 0x7f5de32025b8, 0x10, 0xc000434940)

	/go/pkg/mod/github.com/nwaples/rardecode@v1.1.0/reader.go:221 +0x1b2

github.com/nwaples/rardecode.(*Reader).Next(0xc000272408, 0xc0005a1770, 0x30, 0x28)

	/go/pkg/mod/github.com/nwaples/rardecode@v1.1.0/reader.go:290 +0x65

golift.io/xtractr.(*XFile).unrar(0xc000613c50, 0xc000272400, 0x0, 0x0, 0xc000272400, 0x0, 0x0, 0x0)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/rar.go:34 +0x79

golift.io/xtractr.ExtractRAR(0xc000613c50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/rar.go:24 +0x194

golift.io/xtractr.ExtractFile(0xc000613c50, 0x8fa08a, 0x19, 0xc00018b320, 0x2, 0x2, 0x5, 0xc000613bf0, 0xc000613c58, 0x40d91b)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/files.go:148 +0x88

golift.io/xtractr.(*Xtractr).processArchive(0xc00009ab40, 0xc000a7b1e0, 0xaf, 0xc000500d20, 0x5d, 0x0, 0x0, 0x0, 0xc000613d10, 0x4d40b1, ...)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/queue.go:199 +0x2e5

golift.io/xtractr.(*Xtractr).decompressArchives(0xc00009ab40, 0xc0000c0580, 0x438ebc, 0x203000)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/queue.go:170 +0xf2

golift.io/xtractr.(*Xtractr).decompressFiles(0xc00009ab40, 0xc0000c0580, 0x51, 0x8f40a9)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/queue.go:138 +0x50

golift.io/xtractr.(*Xtractr).extract(0xc00009ab40, 0xc00098ed20)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/queue.go:103 +0x2e6

golift.io/xtractr.(*Xtractr).processQueue(0xc00009ab40)

	/go/pkg/mod/golift.io/xtractr@v0.0.9/queue.go:65 +0x5b

created by golift.io/xtractr.(*Xtractr).Start

	/go/pkg/mod/golift.io/xtractr@v0.0.9/start.go:89 +0xa5
```

**Comment by davidnewhall** [comment]
Does it happen on the same movie or show every time?

**Comment by davidnewhall** [comment]
What is your time zone set to? Do you run this in Docker? Did you set the TZ environment variable? If this is running on linux, what is `/etc/localtime` linked to?

**Comment by davidnewhall** [comment]
Can you share the startup logs?

**Comment by ADRFranklin** [comment]
It happens every so often with different shows/movies, I'm running in docker and my timezone is `Europe/London`. 

```
2021/08/01 06:10:32 Unpackerr v0.9.7 Starting! (PID: 227) 2021-08-01 06:10:32.509630731 +0000 UTC m=+0.021453608

2021/08/01 06:10:32 ==> GoLift Discord: https://golift.io/discord <==

2021/08/01 06:10:32 ==> Startup Settings <==

2021/08/01 06:10:32  => Sonarr Config: 3 servers

2021/08/01 06:10:32  =>    Server: http://sonarr:8989, apikey:true, timeout:10s, verify ssl:false, protos:usenet, delete_orig: false, delete_delay: 5m0s, paths:["/mnt/local/storage/completed/TV"]

2021/08/01 06:10:32  =>    Server: http://sonarr-4k:8989, apikey:true, timeout:10s, verify ssl:false, protos:usenet, delete_orig: false, delete_delay: 5m0s, paths:["/mnt/local/storage/completed/TV-4k"]

2021/08/01 06:10:32  =>    Server: http://sonarr-anime:8989, apikey:true, timeout:10s, verify ssl:false, protos:usenet, delete_orig: false, delete_delay: 5m0s, paths:["/mnt/local/storage/completed/TV-Anime"]

2021/08/01 06:10:32  => Radarr Config: 3 servers

2021/08/01 06:10:32  =>    Server: http://radarr:7878, apikey:true, timeout:10s, verify ssl:false, protos:usenet, delete_orig: false, delete_delay: 5m0s, paths:["/mnt/local/storage/completed/Movies"]

2021/08/01 06:10:32  =>    Server: http://radarr-4k:7878, apikey:true, timeout:10s, verify ssl:false, protos:usenet, delete_orig: false, delete_delay: 5m0s, paths:["/mnt/local/storage/completed/Movies-4k"]

2021/08/01 06:10:32  =>    Server: http://radarr-anime:7878, apikey:true, timeout:10s, verify ssl:false, protos:usenet, delete_orig: false, delete_delay: 5m0s, paths:["/mnt/local/storage/completed/Movies-Anime"]

2021/08/01 06:10:32  => Lidarr Config: 0 servers

2021/08/01 06:10:32  => Readarr Config: 0 servers

2021/08/01 06:10:32  => Folder Config: 0 paths, event buffer: 20000

2021/08/01 06:10:32  => Using Config File: /config/unpackerr.conf

2021/08/01 06:10:32  => Parallel: 1

2021/08/01 06:10:32  => Interval: 2m0s

2021/08/01 06:10:32  => Start Delay: 1m0s

2021/08/01 06:10:32  => Retry Delay: 5m0s, max: 3

2021/08/01 06:10:32  => Debug / Quiet: false / false

2021/08/01 06:10:32  => Directory & File Modes: 0755 & 0644

2021/08/01 06:10:32  => Webhook Configs: 0 URLs
```

**Comment by davidnewhall** [comment]
Thank you!

Can you grep your log for this text `Loading TZ Location` - does it show up at all? Are you setting the TZ variable to `Europe/London`? If not, maybe try that.

**Comment by ADRFranklin** [comment]
TZ is set and set to `Europe/London` and unpackerr is outputting `TZ=Europe/London` 

I don't see any mention of  "Loading TZ Location" in the log though.

**Comment by davidnewhall** [comment]
Okay, I'm a bit stumped. Unpackerr parses TZ on startup and sets `time.Local` to whatever it is. If there is an error paring TZ, it is printed on startup, and the error contains `Loading TZ Location: (error message)`. This error would not go into the unpacker log file, and would likely only show up in `docker logs <container>`.  This is the only thing that comes to mind. The line that is crashing is in a third party library (I opened an issue there), and that line is crashing when using `time.Local`. I think there might be an issue parsing the time zone. Perhaps try unsetting `TZ` to see if this behavior goes away.

**Comment by davidnewhall** [comment]
This seems to work.

```
$ docker run -e TZ=Europe/London golift/unpackerr
2021/08/01 08:57:15 Unpackerr v0.9.7 Starting! (PID: 1) 2021-08-01 08:57:15.690272409 +0100 BST m=+0.000777851
```

**Comment by ADRFranklin** [comment]
Hmm, does seem like an interesting one, I will go ahead and remove the TZ env, and see how that plays out.

I got the logs from docker logs, as I don't even have any log files in config folder. I use a tool called pico for deployment, which is a small single server deployment tool aimed at deploying git repos and using vault (Hashicorp) to set env's when deploying docker containers. The same TZ env is set across all my *arr instances, so I couldn't imagine the TZ itself to be the one causing mishaps here. 

I'll update you if anything else happens.

**Comment by davidnewhall** [comment]
Can you elaborate on this?
> and unpackerr is outputting `TZ=Europe/London`

I may have just forgotten, but where does it output this? I'm still thinking it's not working because your timezone appears to be UTC.

**Comment by ADRFranklin** [comment]
Ignore this part

> and unpackerr is outputting `TZ=Europe/London`

I was using portainer to search, and it picked up the output stuff at the beginning of the docker container, where hotio is outputting the env's.

**Comment by davidnewhall** [comment]
Can you try `golift/unpackerr:latest`? Should drop right in. I'm curious is if that first log line shows the correct time zone with the golift (my) container. Set TZ.

**Comment by ADRFranklin** [comment]
Yeah, can give that a go then.

**Comment by davidnewhall** [comment]
This commit should fit it: https://github.com/davidnewhall/unpackerr/commit/25cb291f1c0949a402109d497424f9f845bc30b7

Please let me know here, or on Discord if you have another crash.
