### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by davidnewhall** [davidnewhall/unpackerr#206]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x7d1461]

goroutine 35 [running]:
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).checkExtractDone(0xc0001759d0)
	/unpackerr/pkg/unpackerr/handlers.go:147 +0x3a1
github.com/davidnewhall/unpackerr/pkg/unpackerr.(*Unpackerr).Run(0xc0001759d0)
	/unpackerr/pkg/unpackerr/start.go:212 +0x1c5
created by github.com/davidnewhall/unpackerr/pkg/unpackerr.Start
	/unpackerr/pkg/unpackerr/start.go:153 +0x3b6
```
```
2022/05/21 07:51:05 Unpackerr v0.10.0 Starting! (PID: 1) 2022-05-21 07:51:05.161003964 -0500 CDT m=+0.048427727
2022/05/21 07:51:05 Missing Lidarr URL in one of your configurations, skipped and ignored.
2022/05/21 07:51:05 [ERROR] Checking Radarr Path: redirected to login page while checking URL http://192.168.1.81:7878: API Key may be incorrect
2022/05/21 07:51:05 [WARN] Sonarr URL fixed: http://192.168.1.81:8989 -> http://192.168.1.81:8989/sonarr (continuing)
2022/05/21 07:51:05 ==> GoLift Discord: https://golift.io/discord <==
2022/05/21 07:51:05 ==> Startup Settings <==
2022/05/21 07:51:05  => Sonarr Config: 1 server: http://192.168.1.81:8989/sonarr, apikey:true, timeout:15s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["mnt/user/mount_mergerfs/GSDrive_Mount/completed"]
2022/05/21 07:51:05  => Radarr Config: 1 server: http://192.168.1.81:7878, apikey:true, timeout:15s, verify ssl:false, protos:torrent, delete_orig: false, delete_delay: 5m0s, paths:["mnt/user/mount_mergerfs/GSDrive_Mount/completed"]
2022/05/21 07:51:05  => Lidarr Config: 0 servers
2022/05/21 07:51:05  => Readarr Config: 0 servers
2022/05/21 07:51:05  => Folder Config: 0 paths, event buffer: 20000
2022/05/21 07:51:05  => Using env variables only. Config file not found.
2022/05/21 07:51:05  => Parallel: 1
2022/05/21 07:51:05  => RAR Passwords: 0
2022/05/21 07:51:05  => Interval: 2m
2022/05/21 07:51:05  => Start Delay: 1m
2022/05/21 07:51:05  => Retry Delay: 5m, max: 3
2022/05/21 07:51:05  => Debug / Quiet: false / false
2022/05/21 07:51:05  => Directory & File Modes: 755 & 644
2022/05/21 07:51:05  => Log File: /downloads/unpackerr.log (10 @ 10Mb)
2022/05/21 07:51:05  => Webhook Configs: 0 URLs
2022/05/21 07:51:05  => Command Hook Configs: 0 cmds
2022/05/21 07:51:05 [ERROR] Radarr (http://192.168.1.81:7878): api.Get(queue): failed:  (status: 302 Found): invalid status code, <200||>299: 
2022/05/21 07:51:05 [Sonarr] Updated (http://192.168.1.81:8989/sonarr): 777 Items Queued
```

**Comment by davidnewhall** [comment]
If you're getting a crash like this, try the docker tag `golift/unpackerr:unstable` and let me know if it fixes it for you.

**Comment by Anon0511** [comment]
Looks good to me. No crashing anymore. Ran it overnight with the same issue beforehand.

**Comment by davidnewhall** [comment]
Thanks I'm going to get a new release - with this fix - out soon.
